# Generated by Django 3.0.3 on 2020-02-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='course',
            new_name='course_id',
        ),
    ]
