# Generated by Django 3.0.3 on 2020-02-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=1200)),
                ('duration', models.CharField(max_length=50)),
                ('video_link', models.CharField(max_length=300)),
                ('content_html_path', models.CharField(max_length=300)),
            ],
        ),
    ]
