# Generated by Django 3.0.3 on 2020-02-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='question_id',
        ),
    ]
